djangoDownloader/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ytDownloader.urls')), # include your app urls
]

ytDownloader/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('', views.index, name='index'),
    path('resolutions/', views.getResolution, name='resolution'),
]

ytDownloader/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    link = models.CharField('Enlace', max_length=120)
    resoluciones = models.CharField('Resoluciones', choices=(), blank=True, null = True, max_length=10)
    nombre = models.CharField('Nombre', blank=True, null = True, max_length=120)
    extension = models.CharField('Extension',  blank=True, null = True, max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self): 
        return self.link + " - " + self.nombre

ytDownloader/forms.py
from django import forms
from ytDownloader.models import Video

class VideoForm(forms.Form):
    
    # def __init__(self, resoluciones=()):
    #     self.resluciones=forms.Field(
    #         widget=forms.widgets.Select(choices=resoluciones,
    #             attrs={
    #                 "class": "form-select"
    #             }
    #         ),
    #         label="Criterio de Búsqueda",
    #     )
    
    enlace = forms.CharField(
       max_length=120,
       required=True,
       widget=forms.widgets.Input (
           attrs={
               "class": "form-control form-control-lg"
           }
       ),
       label="Enlace"
       )

    titulo = forms.CharField(
       max_length=120,
       required=True,
       widget=forms.widgets.Input (
           attrs={
               "class": "form-control form-control-lg",
               "readonly": True
           }
       ),
       label="Titulo de Video"
       )

    resluciones = forms.Field(
       widget=forms.widgets.Select(choices=(),
           attrs={
            "class": "form-select form-select-lg mb-3"
           }
       ),
       label="Resoluciones Disponibles",
    )



    class Meta:
      model = Video
      exclude = ("user",)

ytDownloader/views.py
import os
from django.http import FileResponse, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render
import ffmpeg
from djangoDownloader.settings import BASE_DIR
from datetime import datetime
from ytDownloader.forms import VideoForm
from ytDownloader.models import Video
import mimetypes

from pytube import YouTube

# Create your views here.

def index(request):
    data = None
    if request.method == "POST":
        form = VideoForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)

            s = Video()
            s.link=form.cleaned_data['enlace']
            s.resoluciones=form.cleaned_data['resluciones']
            s.nombre=form.cleaned_data['titulo']
            s.extension=((form.cleaned_data['resluciones'].split(":"))[-1]).strip()
            #print (s)
            
            
            s.save()
            
            fecha_time = s.created_at.strftime("%d-%m-%y %H%M%S")
            filepath = BASE_DIR.__str__() + "\\videos\\"+ str(fecha_time)
            os.mkdir(filepath)
            
            mimetype=((((form.cleaned_data['resluciones'].split(":"))[1]).split(";"))[0]).strip()

            #print(mimetype)
            #print(s.extension)

            url = YouTube(str(form.cleaned_data['enlace']))
            
            video = url.streams.filter(
                resolution=mimetype, 
                mime_type=s.extension, 
                progressive="False").first()

            if not video:
                print ("No progresive = 'False'")
                video = url.streams.filter(
                resolution=mimetype, 
                mime_type=s.extension).first()
                
            archivo = s.nombre+"."+s.extension.split("/")[1]
            
            if video is not None:
                
                if video in url.streams.filter(only_video=True):
                    onlyAudio = url.streams.filter(only_audio=True).first().download(output_path=filepath, filename="only_audio_"+s.nombre+".mp3")
                    onlyVideo = video.download(output_path=filepath, filename="only_video_"+archivo)
                    #print ("a", onlyAudio)
                    #print ("v", onlyVideo)
                    video_file = ffmpeg.input(onlyVideo)
                    audio_file = ffmpeg.input(onlyAudio)
                    print("path_u", os.path.join(filepath, archivo))
                    ffmpeg.concat(video_file, audio_file, v=1, a=1).output("videos\\"+ str(fecha_time) + "\\"+archivo).run()
                else:                     
                    print("Audio & Video")
                    video.download(output_path=filepath, filename=archivo)
                

                myfile = os.path.join(filepath, archivo)
                # print (myfile)
                path_to_file = os.path.realpath(myfile)
                print (path_to_file)
                path = open(path_to_file, 'rb')
                response = HttpResponse(path, content_type='application/video')
                response['Content-Disposition'] = "attachment; filename=%s" % archivo
                return response
            else:
                print("Video no encontrado")
                return None

    else:
        form = VideoForm()
        return render(request, "downloader.html", {"form": form, "data": data})


def getResolution(request):

    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        print('is ajax')
        resoluciones=[]
        if request.method == 'POST':
            data = request.POST
            print(data)
            print(str(data['enlace']))
            url = YouTube(url=str(data['enlace'])) 
            
            streams = url.streams
            print(streams)
            
            for resolucion in url.streams:

                if resolucion.resolution:# and str(resolucion.resolution) not in ("480p", "240p", "144p"):
                    resoluciones.append({'resolucion':str(resolucion.resolution), 'peso':resolucion._filesize_mb, 'format':str(resolucion.mime_type)})
                    
                print(resolucion, '\n')
            
            print (resoluciones)
            titulo=""
            if(url.title):
                print (url.title)
                titulo = url.title
            

        return JsonResponse({'options': resoluciones, 'title': titulo}, status=200)
    
    else:
        return HttpResponseBadRequest('Invalid request')

ytDownloader/templates/downloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Descargador de Videos de YouTube by JhonssonC</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
     integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
     crossorigin=""/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script  src="https://code.jquery.com/jquery-3.6.1.min.js"  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="  crossorigin="anonymous"></script>
</head>
<body class="p-3 m-0 border-0">

    <div class="card text-center">
      <div class="card-header">
        <h3><p class="text-center">Descargador de Video de YouTube</p></h3>
      </div>
      <div class="card-body">
         <div class="container mt-2 px-4 text-center">
            <div class="row">
                <div class="col">
                    <form method="post">{% csrf_token %}

                        {{ form.as_p }}

                        <button id="buscar" type="submit" class="btn btn-primary is-success mt-2">Descargar</button>

                    </form>

                    

                </div>

            </div>

         </div>
      </div>



      <div class="card-footer text-muted">
        By: Jhonsson Córdova D.
      </div>

    </div>

    <script>

    $.when( $.ready ).then(function() {

        function validarURL(miurl) {
          try {
        
            new URL(miurl);
            return true;
        
          } catch (err) {
            
            console.error(err);
            return false;
        
          }
        }

        $("label[for='id_titulo']:first").hide();
        $("#id_titulo").hide();
        $("label[for='id_resluciones']:first").hide();
        $("#id_resluciones").hide();
        $("#buscar").hide();

        $( "#id_enlace" )
          .change(function () {
            let text = $( "#id_enlace" ).val();
            console.log(text);
            if(text.length>8 && validarURL(text)){

              const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
              let serializeData = $(this).serialize();
              
              console.log(serializeData);
              $.ajax({
                url: 'resolutions/',
                type: "POST",
                data: serializeData,
                dataType: "json",
                headers: {'X-CSRFToken': csrftoken},
                success: (data) => {
                  console.log(data);

                  let opciones = data.options

                  opciones.sort((a,b)=>{
                    return b['peso'] - a['peso'];
                  });
                  $('#id_resluciones').html("");
                  for (var index = 0; index < (opciones.length); index++) {
                      if (opciones[index]['peso']>0){
                        let inf = 'Resolución: ' + opciones[index]['resolucion'] + ' ; Peso: ' + opciones[index]['peso'] + 'MB ; Formato: ' + opciones[index]['format']
                        $('#id_resluciones').append('<option value="'+ inf + '">' + inf + '</option>');
                      }
                  }

                  $('#id_titulo').val(data.title);
                  //$("#id_titulo").attr("readonly", true);

                  $("label[for='id_titulo']:first").show();
                  $("#id_titulo").show();
                  $("label[for='id_resluciones']:first").show();
                  $("#id_resluciones").show();
                  $("#buscar").show();

                },
                error: (error) => {
                  console.log(error);
                }
              });

            }
            

          })
          .change();

    });
    </script>


</body>
</html>